### ISSUE TITLE
Problem in loading model mesh

### ISSUE THREAD

**Issue by Mondo92** [caochao39/hku_m100_gazebo#1]
Hi!
Every time I try to roslaunch the empty_world launch file this error occurs:
![schermata 2017-06-06 alle 14 04 43](https://cloud.githubusercontent.com/assets/17549078/26828452/c3c61b92-4ac1-11e7-8921-323d35794409.png)
It seems that the model has been correctly imported in Gazebo but it cannot find the mesh. 
How can I fix this problem?
I'm using Ubuntu 14.04 + ROS Indigo. Gazebo 2.2.3.

**Comment by Kanelankai** [comment]
@Mondo92 Hello!
I have met the same problem.
Could you tell me how you solved it?
Thank you!
